"""Tests for foundation question-bank routing."""

import importlib.util
import os
import sys
from pathlib import Path
from unittest.mock import MagicMock

_zerde = os.path.join(os.path.dirname(__file__), "..", "src", "shared", "python")
if _zerde not in sys.path:
    sys.path.insert(0, _zerde)

os.environ.setdefault("BOT_TOKEN", "test-bot-token")
os.environ.setdefault("TABLE_NAME", "test-quiz-table")
os.environ.setdefault("GEMINI_API_KEY", "test-gemini-key")
os.environ.setdefault("QUIZ_LLM_RPD", "1000")
os.environ.setdefault("DEEPSEEK_API_KEY", "test-deepseek-key")

_quiz_dir = os.path.join(os.path.dirname(__file__), "..", "src", "quiz")
_saved_modules: dict[str, object] = {}

try:
    for mod_name in list(sys.modules):
        if mod_name in ("core", "services") or mod_name.startswith(("core.", "services.")):
            _saved_modules[mod_name] = sys.modules.pop(mod_name)

    sys.path.insert(0, _quiz_dir)
    from services.quiz_service import QuizService  # noqa: E402
finally:
    if _quiz_dir in sys.path:
        sys.path.remove(_quiz_dir)
    for mod_name in list(sys.modules):
        if mod_name in ("core", "services") or mod_name.startswith(("core.", "services.")):
            sys.modules.pop(mod_name, None)
    sys.modules.update(_saved_modules)


def _make_service() -> QuizService:
    svc = QuizService.__new__(QuizService)
    svc._generator = MagicMock()
    svc._sender = MagicMock()
    svc._repo = MagicMock()
    return svc


def _bank_item() -> dict:
    return {
        "question": "Which AWS service stores objects?",
        "options": ["S3", "EC2", "IAM", "VPC"],
        "correct_option_id": 0,
        "explanation": "S3 is object storage.",
    }


def test_clf_bank_serves_easy_with_difficulty_specific_queue() -> None:
    svc = _make_service()
    svc._repo.get_question_queue.return_value = []
    svc._repo.get_bank_question_ids.return_value = ["aws-clf-c02::q1"]
    svc._repo.get_bank_question.return_value = _bank_item()

    result = svc._pick_banked_question_for_chat("cloud", "-100123", "easy")

    assert result is not None
    question, remaining = result
    assert question["question"] == "Which AWS service stores objects?"
    assert question["difficulty"] == "easy"
    assert question["points"] == 1
    assert remaining == []
    svc._repo.get_question_queue.assert_called_once_with("cloud", "-100123", "easy")
    svc._repo.get_bank_question_ids.assert_called_once_with(
        "cloud",
        ["aws-clf-c02"],
        allowed_difficulties={"easy"},
    )


def test_clf_bank_does_not_serve_medium_or_harder_requests() -> None:
    svc = _make_service()

    result = svc._pick_banked_question_for_chat("cloud", "-100123", "medium")

    assert result is None
    svc._repo.get_question_queue.assert_not_called()
    svc._repo.get_bank_question_ids.assert_not_called()
    svc._repo.get_bank_question.assert_not_called()


def test_genquiz_aws_medium_falls_back_to_ai_instead_of_clf_bank() -> None:
    svc = _make_service()
    svc._generator.generate_question.return_value = {
        "question": "A workload needs multi-AZ failover. What should you choose?",
        "options": ["A", "B", "C", "D"],
        "correct_option_index": 0,
        "explanation": "Use a resilient design.",
        "difficulty": "medium",
        "points": 3,
    }
    svc._sender.send_quiz_poll.return_value = {"poll": {"id": "poll-ai"}, "message_id": 7}
    svc._repo.save_quiz_record.return_value = True

    result = svc.process_on_demand_quiz("-100123", "en", "aws", "medium")

    assert result == {"status": "ok", "sent": 1, "total": 1}
    svc._repo.get_genquiz_question_queue.assert_not_called()
    svc._repo.get_bank_question_ids.assert_not_called()
    svc._generator.generate_question.assert_called_once_with("aws", "en", "medium")


def test_genquiz_dva_does_not_use_clf_foundation_bank() -> None:
    svc = _make_service()
    svc._generator.generate_question.return_value = {
        "question": "Which service packages deployment artifacts?",
        "options": ["A", "B", "C", "D"],
        "correct_option_index": 0,
        "explanation": "Generated by AI until a DVA bank exists.",
        "difficulty": "easy",
        "points": 1,
    }
    svc._sender.send_quiz_poll.return_value = {"poll": {"id": "poll-dva"}, "message_id": 9}
    svc._repo.save_quiz_record.return_value = True

    result = svc.process_on_demand_quiz("-100123", "en", "dva", "easy")

    assert result == {"status": "ok", "sent": 1, "total": 1}
    svc._repo.get_genquiz_question_queue.assert_not_called()
    svc._repo.get_bank_question_ids.assert_not_called()
    svc._generator.generate_question.assert_called_once_with("dva", "en", "easy")


def test_daily_ai_quiz_uses_subtopic_deck_and_saves_it_after_send() -> None:
    svc = _make_service()
    svc.get_difficulty = MagicMock(return_value="medium")
    svc._repo.get_today_quiz_record.return_value = None
    svc._repo.get_category_queue.return_value = ["networking"]
    svc._repo.get_subtopic_queue.return_value = ["DNS / TTL", "HTTP / caching"]
    svc._repo.get_question_queue.return_value = []
    svc._repo.get_bank_question_ids.return_value = []
    svc._generator.generate_question.return_value = {
        "question": "A DNS record changed but users still hit the old IP. Why?",
        "options": ["TTL caching", "TLS expired", "TCP reset", "CIDR overlap"],
        "correct_option_index": 0,
        "explanation": "Resolvers may cache records until TTL expires.",
        "difficulty": "medium",
        "points": 3,
        "subtopic": "DNS / TTL",
        "fingerprint": "fp-dns",
    }
    svc._sender.send_message.return_value = True
    svc._sender.send_quiz_poll.return_value = {"poll": {"id": "poll-daily"}, "message_id": 42}
    svc._repo.save_quiz_record.return_value = True

    result = svc.process_daily_quiz(["-100123"], "en")

    assert result["sent"] == 1
    svc._generator.generate_question.assert_called_once_with("networking", "en", "medium", "DNS / TTL")
    svc._repo.save_quiz_record.assert_called_once()
    assert svc._repo.save_quiz_record.call_args.kwargs["subtopic"] == "DNS / TTL"
    assert svc._repo.save_quiz_record.call_args.kwargs["fingerprint"] == "fp-dns"
    svc._repo.save_subtopic_queue.assert_called_once_with(
        "-100123",
        "networking",
        "medium",
        ["HTTP / caching"],
        "DNS / TTL",
    )


def test_daily_quiz_prefers_ai_generated_bank_for_selected_subtopic() -> None:
    svc = _make_service()
    svc.get_difficulty = MagicMock(return_value="medium")
    svc._repo.get_today_quiz_record.return_value = None
    svc._repo.get_category_queue.return_value = ["database"]
    svc._repo.get_subtopic_queue.return_value = ["indexes / transactions"]
    svc._repo.get_question_queue.return_value = []
    svc._repo.get_bank_question_ids.return_value = []
    svc._repo.get_question_queue.return_value = []
    svc._repo.get_bank_question_ids.return_value = ["ai-generated::q1"]
    svc._repo.get_bank_question.return_value = {
        "question": "A query filters by user_id and status. What helps most?",
        "options": ["Composite index", "More rows", "Larger page size", "Manual backup"],
        "correct_option_id": 0,
        "explanation": "A composite index can match both predicates.",
        "subtopic": "indexes / transactions",
        "fingerprint": "fp-bank",
    }
    svc._sender.send_message.return_value = True
    svc._sender.send_quiz_poll.return_value = {"poll": {"id": "poll-bank"}, "message_id": 99}
    svc._repo.save_quiz_record.return_value = True

    result = svc.process_daily_quiz(["-100123"], "en")

    assert result["sent"] == 1
    svc._generator.generate_question.assert_not_called()
    svc._repo.save_question_queue.assert_called_once()
    assert svc._repo.save_question_queue.call_args.args[:4] == ("database", "-100123", [], "medium")
    assert "ai-generated" in svc._repo.save_question_queue.call_args.args[4]
    svc._repo.mark_bank_question_used.assert_called_once_with("database", "ai-generated", "q1")


def test_daily_ai_quiz_does_not_commit_subtopic_deck_when_poll_send_fails() -> None:
    svc = _make_service()
    svc.get_difficulty = MagicMock(return_value="medium")
    svc._repo.get_today_quiz_record.return_value = None
    svc._repo.get_category_queue.return_value = ["database"]
    svc._repo.get_subtopic_queue.return_value = ["indexes / transactions"]
    svc._repo.get_question_queue.return_value = []
    svc._repo.get_bank_question_ids.return_value = []
    svc._generator.generate_question.return_value = {
        "question": "Which index helps this query?",
        "options": ["A", "B", "C", "D"],
        "correct_option_index": 0,
        "explanation": "Use the matching index.",
        "difficulty": "medium",
        "points": 3,
        "subtopic": "indexes / transactions",
        "fingerprint": "fp-db",
    }
    svc._sender.send_message.return_value = True
    svc._sender.send_quiz_poll.return_value = None

    result = svc.process_daily_quiz(["-100123"], "en")

    assert result["failed"] == [{"chat_id": "-100123", "step": "sendPoll"}]
    svc._repo.save_subtopic_queue.assert_not_called()


def test_question_bank_builder_tops_up_and_skips_duplicate_fingerprint() -> None:
    svc = _make_service()
    svc._repo.get_bank_question_summaries.return_value = []
    svc._repo.save_generated_bank_question.return_value = True
    svc._generator.generate_question.side_effect = [
        {
            "question": "What does DNS TTL control?",
            "options": ["Cache lifetime", "Packet size", "TLS cipher", "Subnet mask"],
            "correct_option_index": 0,
            "explanation": "TTL controls resolver cache duration.",
            "difficulty": "easy",
            "points": 1,
            "subtopic": "DNS / TTL",
            "fingerprint": "fp-ttl",
        },
        {
            "question": "What does DNS TTL control?",
            "options": ["Cache lifetime", "Packet size", "TLS cipher", "Subnet mask"],
            "correct_option_index": 0,
            "explanation": "TTL controls resolver cache duration.",
            "difficulty": "easy",
            "points": 1,
            "subtopic": "DNS / TTL",
            "fingerprint": "fp-ttl",
        },
    ]

    result = svc.build_generated_question_bank(
        max_questions=2,
        target_per_combo=2,
        categories=["networking"],
        difficulties=["easy"],
        subtopics_by_category={"networking": ["DNS / TTL"]},
    )

    assert result["created"] == 1
    assert result["skipped_existing"] == 1
    svc._repo.save_generated_bank_question.assert_called_once()
    saved_question = svc._repo.save_generated_bank_question.call_args.args[2]
    assert saved_question["difficulty_band"] == "ai-generated"


def test_clf_import_items_are_foundation_metadata() -> None:
    script_path = Path(__file__).resolve().parents[1] / "dev" / "scrapers" / "import_questions.py"
    spec = importlib.util.spec_from_file_location("import_questions", script_path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    item = module._build_item(
        "BANK#cloud#aws-clf-c02",
        {
            "uuid": "q1",
            "domain": "Domain 2: Security and Compliance",
            "question": "Which service manages AWS user permissions?",
            "options": ["IAM", "S3", "EC2", "Route 53"],
            "correct_option_id": "0",
            "explanation": "IAM manages identities and access.",
            "exam_name": "CLF-C02",
        },
        "aws-clf-c02",
        "cloud",
    )

    assert item["difficulty"] == "easy_medium"
    assert item["difficulty_band"] == "foundation"
    assert item["subtopic"] == "iam"
    assert len(item["fingerprint"]) == 40
